"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.loginUserController = exports.getAllUserController = exports.createUserController = exports.loginUserUseCase = exports.getAllUseCase = exports.createUserUseCase = exports.mysqlUserRepository = void 0;
const CreateUserUseCase_1 = require("../application/CreateUserUseCase");
const GetAllUserUseCase_1 = require("../application/GetAllUserUseCase");
const LogInUserUseCase_1 = require("../application/LogInUserUseCase");
const CreateUserController_1 = require("./controllers/CreateUserController");
const GetAllUserController_1 = require("./controllers/GetAllUserController");
const LoginUserController_1 = require("./controllers/LoginUserController");
const MysqlUserRepository_1 = require("./MysqlUserRepository");
exports.mysqlUserRepository = new MysqlUserRepository_1.MysqlUserRepository();
exports.createUserUseCase = new CreateUserUseCase_1.CreateUserUseCase(exports.mysqlUserRepository);
exports.getAllUseCase = new GetAllUserUseCase_1.GetAllUserUseCase(exports.mysqlUserRepository);
exports.loginUserUseCase = new LogInUserUseCase_1.LoginUserUseCase(exports.mysqlUserRepository);
exports.createUserController = new CreateUserController_1.CreateUserController(exports.createUserUseCase);
exports.getAllUserController = new GetAllUserController_1.GetAllUserController(exports.getAllUseCase);
exports.loginUserController = new LoginUserController_1.LoginUserController(exports.loginUserUseCase);
